import {
  widthPixel,
  heightPixel,
  fontPixel,
  pixelSizeHorizontal,
  pixelSizeVertical,
} from '@utils/normalize';
import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  sidebar_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    flex: 1,
    margin: 0,
    padding: 0,
    paddingBottom: pixelSizeVertical(50),
  },
  header: {
    backgroundColor: '#27AD80',
    width: '100%',
    height: heightPixel(315),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    paddingLeft: pixelSizeHorizontal(108),
    paddingRight: pixelSizeHorizontal(35),
    marginTop: pixelSizeVertical(-55),
  },
  phone_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',

    width: '100%',
  },
  phone_icon_wrapper: {
    width: widthPixel(24),
    height: heightPixel(24),
    marginHorizontal: pixelSizeHorizontal(10),
  },
  profile_pic_wrapper: {
    width: widthPixel(80),
    height: heightPixel(80),
    borderRadius: 40,
    marginTop: pixelSizeVertical(66),
  },
  name: {
    color: '#ffffff',
    textTransform: 'capitalize',
    fontWeight: '600',
    fontSize: fontPixel(17),
    lineHeight: fontPixel(22),
    width: widthPixel(200),
    marginTop: pixelSizeVertical(50),
    textAlign: 'right',
  },
  id: {
    color: '#ffffff',
    textTransform: 'uppercase',
    fontSize: fontPixel(15),
    lineHeight: fontPixel(20),
    textAlign: 'right',
    marginTop: pixelSizeVertical(7),
  },
  menu_item_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    paddingVertical: pixelSizeVertical(34),
    //paddingLeft: pixelSizeHorizontal(55),
    paddingRight: pixelSizeHorizontal(32),
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
  },
  menu_item: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: '100%',
    marginVertical: pixelSizeVertical(8.5),
  },
  menu_label: {
    color: '#1c1c1c',
    fontSize: fontPixel(15),
    lineHeight: fontPixel(20),
    textTransform: 'capitalize',
  },
  icon_wrapper: {
    width: widthPixel(35),
    height: heightPixel(35),
    borderRadius: 35,
    backgroundColor: 'rgba(39,173,128,0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: pixelSizeHorizontal(10),
  },
});
export default styles;
