import {
  heightPixel,
  widthPixel,
  pixelSizeHorizontal,
  fontPixel,
  pixelSizeVertical,
} from '@utils/normalize';
import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  patient_wrapper_24_7: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    backgroundColor: 'white',
    paddingHorizontal: pixelSizeHorizontal(36),
    //@ts-ignore
    ...StyleSheet.absoluteFill
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: '100%',
  },
  back_icon_wrapper: {
    height: heightPixel(16),
    width: widthPixel(9.26),
  },
  back_btn_wrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    position: 'absolute',
    left: 10,
  },
  title: {
    textAlign: 'left',
    marginHorizontal: 'auto',
    width: widthPixel(166),
    fontSize: fontPixel(24),   
    lineHeight: fontPixel(36),
    color: '#1c1c1c',
    fontWeight: '700',
  },
  doctor_header: {
    marginTop: pixelSizeVertical(33),
  },
  heading: {
    marginTop: pixelSizeVertical(46),
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    textTransform: 'capitalize',
    fontWeight: '600',
    color: '#1c1c1c',
    marginBottom: pixelSizeVertical(27),
  },
  prescriptions_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: pixelSizeVertical(5),
    paddingHorizontal: pixelSizeHorizontal(15),
    backgroundColor: 'rgba(39,173,128,0.1)',
    borderRadius: 13,
    width: widthPixel(300),
    height: heightPixel(51),
    marginTop: pixelSizeVertical(34),
  },
  prescription_text: {
    color: '#1c1c1c',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    fontWeight: '700',
  },
  arrow_wrapper: {
    width: widthPixel(33),
    height: heightPixel(13.21),
    marginLeft: pixelSizeHorizontal(24),
  },
  checkbox_text: {
    color: '#686868',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
    marginLeft: pixelSizeHorizontal(10),
  },
  check_box_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginVertical: pixelSizeVertical(26),
    marginRight: 'auto',
    marginLeft: pixelSizeHorizontal(7.5),
  },
  btn_wrapper: {
    marginTop: pixelSizeVertical(41),
    width: widthPixel(300),
    height: heightPixel(66), 
  },
  horizontal_line: {
    height: 1,
    width: widthPixel(300),
    marginHorizontal: 'auto',
    borderStyle: 'solid',
    borderBottomColor: '#000000',
    borderBottomWidth: 1,
    marginTop: pixelSizeVertical(16.5),
  },
  options_title: {
    color: '#1c1c1c',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    fontWeight: '500',
    marginTop: pixelSizeVertical(22.5),
    textTransform: 'capitalize',
  },
  calls_btns_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    marginVertical: pixelSizeVertical(25),
  },
  btn_item: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  btn_icon_wrapper: {
    width: widthPixel(62),
    height: heightPixel(55),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#27AD80',
    borderWidth: 1,
    borderRadius: 7,
    marginHorizontal: pixelSizeHorizontal(25),
  },
  btn_text: {
    color: '#27AD80',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
    textTransform: 'capitalize',
    marginTop: pixelSizeVertical(17),
  },
});

export default styles;
