import {
  widthPixel,
  heightPixel,
  fontPixel,
  pixelSizeVertical,
  pixelSizeHorizontal,
} from '@utils/normalize';
import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  information_qa_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    backgroundColor: 'white',
    paddingHorizontal: pixelSizeHorizontal(36),
  },

  linearGradient: {
    width: widthPixel(300),
    height: heightPixel(20),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
  },
  complete_label_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: pixelSizeVertical(36),
  },
  complete_label: {
    fontSize: fontPixel(13),
    lineHeight: fontPixel(21),
    color: '#1c1c1c',
    textTransform: 'capitalize',
  },
  percent_sign: {
    color: '#27AD80',
  },
  progress_bar: {
    width: widthPixel(23),
    height: heightPixel(16),
    backgroundColor: '#27AD80',
    borderRadius: 23.5,
    alignSelf: 'flex-start',
  },
  form_wrapper: {
    marginTop: pixelSizeVertical(44),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
  },
  label: {
    color: '#1C1C1C',
    fontWeight: '500',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    textTransform: 'capitalize',
  },
  text_input: {
    marginTop: pixelSizeVertical(30),
    width: widthPixel(283),
    height: heightPixel(45),
    borderRadius: 4,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#686868',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(16),
    paddingVertical: 0,
  },
  next_btn: {
    width: widthPixel(300),
    height: heightPixel(60),
    marginTop: pixelSizeVertical(71),
  },
  back_btn: {
    width: widthPixel(100),
    height: heightPixel(30),
    marginTop: pixelSizeVertical(15),
    alignSelf: 'center',
  },
  checkboxes_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  checkbox_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: pixelSizeVertical(5),
  },
  checkbox_label: {
    color: '#686868',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
    textTransform: 'capitalize',
    marginLeft: pixelSizeHorizontal(6),
  },
  selected_checkbox_label: {
    color: '#27AD80',
  },
  row_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },

  calendar_icon_wrapper: {
    width: widthPixel(33),
    height: heightPixel(37),
    marginLeft: pixelSizeHorizontal(5),
    marginTop: pixelSizeVertical(25),
  },
  height_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: heightPixel(37),
    marginTop: pixelSizeVertical(24),
  },
  height_input: {
    width: widthPixel(57),
    height: heightPixel(37),
    alignSelf: 'center',
    marginTop: 0,
  },
  unit_text: {
    color: '#686868',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
    marginLeft: pixelSizeHorizontal(10),
  },
  weight_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: pixelSizeVertical(24),
  },
  weight_input: {
    width: widthPixel(198),
    height: heightPixel(37),
    marginTop: 0,
  },
  blood_grp_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: pixelSizeVertical(24),
  },
  blood_group_text_input: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderStyle: 'solid',
    borderColor: '#686868',
    borderWidth: 1,
    width: widthPixel(292),
    height: heightPixel(37),
    marginTop: pixelSizeVertical(19),
    paddingVertical: 0,
  },
  blood_group_input: {
    backgroundColor: 'transparent',
    width: widthPixel(270),
    height: heightPixel(37),
    fontSize: fontPixel(10),
    lineHeight: fontPixel(12),
  },
  skip_btn: {
    width: widthPixel(133),
    height: heightPixel(32),
    borderRadius: 15,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#27AD80',
    marginTop: pixelSizeVertical(42),
    alignSelf: 'flex-end',
    paddingHorizontal: pixelSizeHorizontal(12),
  },
  skip_text: {
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
    fontWeight: '600',
    alignSelf: 'center',
    textTransform: 'capitalize',
    color: 'white',
    marginLeft: 'auto',
  },
  skip_icon: {
    width: widthPixel(17),
    height: heightPixel(17),
    justifyContent: 'flex-end',
    marginLeft: 'auto',
  },
  height_errors_wrapper: {
    marginVertical: pixelSizeVertical(16),
  },
  diseases_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    height: heightPixel(300),
    width: '100%',
    marginTop: pixelSizeVertical(25),
  },
  diseases_checkbox: {
    width: '100%',
  },
  input_wrapper: {
    marginVertical: pixelSizeVertical(10),
    width: '100%',
    height: heightPixel(100),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
});

export default styles;
