import {
  fontPixel,
  heightPixel,
  pixelSizeHorizontal,
  pixelSizeVertical,
  widthPixel,
} from '@utils/normalize';
import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  prescriptions_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    backgroundColor: 'white',
    flex: 1,
    height: '100%',
    paddingHorizontal: pixelSizeHorizontal(25),
    paddingBottom: pixelSizeVertical(5),
  },
  new_prescription_label: {
    color: '#828282',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
    fontWeight: 'bold',
    textTransform: 'capitalize',
    textAlign: 'left',
    marginBottom: pixelSizeVertical(7),
  },
  patient_info_wrapper: {
    width: widthPixel(300),
    height: heightPixel(96),
    borderRadius: 13,
    backgroundColor: 'rgba(39,173,128,0.1)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: pixelSizeHorizontal(20),
  },
  patient_name: {
    color: '#1c1c1c',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    textTransform: 'capitalize',
    fontWeight: 'bold',
  },
  patient_info: {
    color: '#686868',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(21),
  },
  complains_label: {
    color: '#1c1c1c',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    marginTop: pixelSizeVertical(43),
  },
  add_prescription_item_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: widthPixel(302),
    height: heightPixel(45),
    backgroundColor: '#FAF9FC',
    borderRadius: 73,
    marginTop: pixelSizeVertical(15),
  },
  input_wrapper: {
    width: fontPixel(253),
    height: '100%',
    paddingHorizontal: pixelSizeHorizontal(10),
  },
  add_btn_wrapper: {
    borderRadius: 20,
    backgroundColor: '#27AD80',
    width: widthPixel(49),
    height: heightPixel(45),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  prescription_items_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: pixelSizeVertical(22),
  },
  prescription_item: {
    borderRadius: 8,
    backgroundColor: 'rgba(39,173,128,0.1)',
    width: widthPixel(276),
    height: heightPixel(34),
    marginVertical: pixelSizeVertical(2.5),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: pixelSizeHorizontal(8),
  },
  prescription_text: {
    color: '#1c1c1c',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(24),
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  delete_wrapper: {
    width: widthPixel(19),
    height: heightPixel(20),
  },
  next_btn: {
    width: widthPixel(221),
    height: heightPixel(51),
    alignSelf: 'center',
    marginTop: pixelSizeVertical(25),
  },
  diagnosis_text: {
    color: 'rgba(104,104,104,0.6)',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
  },
  picker_wrapper: {
    display: 'none',
  },
  medicine_item: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(39,173,128,0.1)',
    width: widthPixel(271),
    height: heightPixel(81),
    paddingVertical: pixelSizeVertical(10),
    paddingHorizontal: pixelSizeHorizontal(18.65),
    borderRadius: 20,
    marginVertical: pixelSizeVertical(10),
  },
  content_wrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    height: '100%',
  },
  content_text: {
    color: '#2E353D',
    fontSize: fontPixel(13),
    lineHeight: fontPixel(24),
  },
  edit_icon: {
    width: widthPixel(25),
    height: heightPixel(21),
  },
  del_icon: {
    width: widthPixel(21),
    height: heightPixel(22),
  },
  follow_up_btn_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: widthPixel(182),
    marginBottom: pixelSizeVertical(43),
  },
  follow_up_btn: {
    width: widthPixel(70),
    height: heightPixel(32),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    backgroundColor: 'white',
    elevation: 3,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowOffset: {
      width: widthPixel(0),
      height: heightPixel(5),
    },
  },
  follow_btn_text: {
    color: '#1c1c1c',
    fontSize: fontPixel(11),
    lineHeight: fontPixel(13),
    textTransform: 'capitalize',
  },
  no_btn: {
    borderColor: '#F10C0C',
    borderWidth: 1,
    borderStyle: 'solid',
  },
  yes_btn: {
    borderColor: '#27AD80',
    borderWidth: 1,
    borderStyle: 'solid',
  },
});

export default styles;
