import {
  fontPixel,
  pixelSizeVertical,
  pixelSizeHorizontal,
  heightPixel,
  widthPixel,
} from '@utils/normalize';
import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  available_hours: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    backgroundColor: 'white',
    paddingHorizontal: pixelSizeHorizontal(30),
  },
  heading: {
    color: '#1c1c1c',
    fontSize: fontPixel(16),
    lineHeight: fontPixel(24),
    fontWeight: '500',
    marginTop: pixelSizeVertical(12),
  },
  days_wrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: pixelSizeVertical(12),
    marginBottom: pixelSizeVertical(28),
  },
  day_label: {
    color: '#686868',
    fontSize: fontPixel(13),
    lineHeight: fontPixel(24),
    textTransform: 'capitalize',
    marginTop: pixelSizeVertical(16),
  },
  day_item: {
    width: widthPixel(32.35),
    height: heightPixel(19),
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    marginHorizontal: pixelSizeHorizontal(10),
  },
  selected_day_item: {
    backgroundColor: '#27AD80',
    width: widthPixel(32.35),
    height: heightPixel(19),
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: pixelSizeHorizontal(9),
    borderRadius: 4,
    display: 'flex',
  },
  day_text: {
    color: '#27AD80',
    fontSize: fontPixel(11),
    lineHeight: fontPixel(13),
    textTransform: 'uppercase',
  },
  selected_day_text: {
    color: '#ffffff',
    fontSize: fontPixel(11),
    lineHeight: fontPixel(19),
    textTransform: 'uppercase',
  },
  slot_wrapper: {
    width: widthPixel(300),
    height: heightPixel(64),
    elevation: 3,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowOffset: {
      width: widthPixel(5),
      height: heightPixel(5),
    },
    backgroundColor: '#ffffff',
    borderRadius: 15,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: pixelSizeHorizontal(20),
    justifyContent: 'center',
    marginVertical: pixelSizeVertical(13),
  },
  slot_label: {
    color: '#686868',
    fontSize: fontPixel(11),
    lineHeight: fontPixel(16),
    textTransform: 'capitalize',
  },
  slot_time: {
    color: '#2D2D2D',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(20),
    textTransform: 'uppercase',
    fontWeight: '500',
  },
  confirm_wrapper: {
    backgroundColor: '#27AD80',
    width: widthPixel(300),
    height: heightPixel(60),
    borderRadius: 15,
    shadowColor: '#000000',
    marginTop: pixelSizeVertical(10),
    shadowOffset: {
      width: widthPixel(5),
      height: heightPixel(10),
    },
  },
  mini_slot: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: widthPixel(300),
    height: heightPixel(36),
    borderRadius: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowOffset: {
      width: widthPixel(5),
      height: heightPixel(5),
    },
    elevation: 3,
    backgroundColor: 'white',
    marginTop: pixelSizeVertical(39),
  },
  mini_slot_grey_text: {
    color: '#686868',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(20),
    textTransform: 'uppercase',
  },
  mini_slot_green_text: {
    color: '#27AD80',
    fontSize: fontPixel(14),
    lineHeight: fontPixel(20),
    textTransform: 'uppercase',
  },
});

export default styles;
